name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Build the app
        run: yarn build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        env:
          NODE_DEBUG: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_history: true
          build_dir: public
