name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      # start
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: dependency-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # end
      - name: Install dependencies
#         if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline
      - name: Build the app
        run: yarn build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        env:
          NODE_DEBUG: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_history: true
          build_dir: public
